### ISSUE TITLE
Incompatible with poetry 1.2 release

### ISSUE THREAD

**Issue by Handfeger** [igmk/ac3airborne#2]
Since the new release of [poetry](https://python-poetry.org) enforces [PEP440](https://peps.python.org/pep-0440/) the version number `v0.0.6-24-g4e7feb4 4e7feb4` is no longer supported.
A valid version number would be `0.0.6+4e7feb4`. The current version of `versioneer` supports PEP440, so a new release may fix this problem.

This is also shown by running `python setup.py version` in the root directory:
```error
UserWarning: The version specified ('v0.0.6-24-g4e7feb4') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by mariomech** [comment]
Ok, I see. I just created a new release with the number 0.1.0. This hopefully fixes the problem.
